spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/parthcs-secondary/config-server-prop.git
          username: parthcs-secondary
          password: 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
          skipSslValidation: true
  application:
    name: config-server
server:
  port: 8888